services:
    bot:
        build: .
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        command: python -m src.main
        depends_on:
            - db

    db:
        image: postgres:17.2
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - data:/var/lib/postgresql/data
        logging:
            driver: "json-file"
            options:
                max-size: "3m"
                max-file: "1"

volumes:
    data:
